name: pbp_update

# Controls when the action will run.
on:
  schedule:
    - cron:  '25 19 * * *'

jobs: 
  get-pbp:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Load repo and install R
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Query dependencies
        run: |
          install.packages('DBI')
          install.packages('duckdb')
          install.packages('tibble')
          install.packages('dplyr')
          install.packages('hoopR')
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
    # Run R script
      - name: Generate data
        run: |
          source("./gha_scripts/pbp_data_update.R")
        shell: Rscript {0} 
      
 # Add duckdb files, commit, and push
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add sq-db.duckdb
        git commit -am "PBP UPDATE"
        git push origin main
